# -*- coding: utf-8 -*-
"""KMeans Clustering (Task).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MTOCbkhKno73hqBSxhbJpakj00Fp4pb8
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

file = "mall_customer.csv"

mc = pd.read_csv(file)

mc.head()

features = ['Annual_Income_(k$)', 'Spending_Score']
mcF = mc[features]

mcF

plt.scatter(mcF['Annual_Income_(k$)'], mcF['Spending_Score'], c = "salmon");

kmeans = KMeans(n_clusters=4)
kmeans.fit(mcF)
y_kmeans = kmeans.predict(mcF)

plt.scatter(mcF['Annual_Income_(k$)'], mcF['Spending_Score'], c=y_kmeans, s=50, cmap='inferno')

centers = kmeans.cluster_centers_
centers
plt.scatter(centers[:, 0], centers[:, 1], c='black', s=200, alpha=0.5);